// job_controller.dart
import 'package:job_app/app_imports.dart';
import 'package:job_app/mvvm/model/job_model.dart';

class JobController extends GetxController {
  // 1. Observable List of Jobs
  // .obs makes this list reactive. Any widget using it updates automatically.
  final RxList<JobModel> jobList = <JobModel>[].obs;

  // Initial dummy data (to be replaced by API calls in a real app)
  // @override
  // void onInit() {
  //   super.onInit();
  // }

  // 3. Function to add a new job
  void addJob(String positionName, String description) {
    // Create a new unique ID (for demonstration, normally generated by the database)
    final newId = DateTime.now().millisecondsSinceEpoch.toString();

    final newJob = JobModel(
      id: newId,
      positionName: positionName,
      // location: location,
      description: description,
    );

    // Add the new job to the observable list
    jobList.add(newJob);

    // Navigate back after adding
    Get.back();

    Get.snackbar(
      "Success",
      "Job Post Added Successfully!",
      snackPosition: SnackPosition.BOTTOM,
      backgroundColor: AppColors.successGreen,
      colorText: AppColors.white,
      margin: EdgeInsets.all(16),
    );
  }

  // New: Function to delete a job
  void deleteJob(String jobId) {
    // 1. Remove the job from the reactive list based on its ID
    jobList.removeWhere((job) => job.id == jobId);
    Get.snackbar(
      "Deleted",
      "Job post removed successfully!",
      snackPosition: SnackPosition.BOTTOM,
      backgroundColor: Colors.red,
      colorText: Colors.white,
    );
  }
}
